# Generated by Django 5.2.8 on 2025-11-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('Tarjeta', 'Tarjeta')], default='Tarjeta', max_length=50),
        ),
    ]
