# Generated by Django 5.2.8 on 2025-11-26 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0002_alter_pago_metodo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pago',
            table='servicios_pago',
        ),
    ]
