# Generated by Django 5.2.8 on 2025-11-26 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_usuario_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='avatar',
        ),
    ]
