# Generated by Django 5.2.7 on 2025-11-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ruta', models.CharField(max_length=100)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('paradas', models.JSONField()),
                ('link', models.URLField(max_length=255)),
                ('imagen', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva')], default='Activa', max_length=20)),
                ('tipo', models.CharField(choices=[('Urbana', 'Urbana'), ('Interurbana', 'Interurbana'), ('Interdepartamental', 'Interdepartamental')], default='Urbana', max_length=30)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rutas_buses',
                'managed': True,
            },
        ),
    ]
