# Generated by Django 5.2.7 on 2025-11-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rutas', '0002_rutabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutabus',
            name='tarifa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
